version: "3.8"

services:
  iris-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${PORT:-5173}:5173"
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true
