// src/rooms/roomConfig.ts
export interface RoomConfig {
  id: string
  name: string
  subtitle: string
  tags: string[]
  relayUrl?: string
  sound?: string
  icon?: string
  externalUrl?: string
  default?: boolean
}

export const ROOM_CONFIGS: Record<string, RoomConfig> = {
  square: {
    id: "square",
    name: "Town Square",
    subtitle: "Public discourse",
    tags: [
      "public",
      "discussion",
      "social",
      "neutral",
      "debate",
      "religion",
      "politics",
      "believer",
      "faith",
    ],
    sound: "sounds/town-ambience.mp3",
    icon: "town-square.png",
    default: true,
  },
  atheism: {
    id: "atheism",
    name: "Atheism",
    subtitle: "Reason",
    tags: ["atheism", "skepticism", "reason", "freethinker", "freethought", "evolution"],
    sound: "sounds/door-sound.mp3",
    icon: "atheism.png",
  },
  church: {
    id: "church",
    name: "Church",
    subtitle: "Christian community",
    tags: [
      "church",
      "christianity",
      "catholicism",
      "faith",
      "protestant",
      "orthodox",
      "presbyterian",
      "evangelical",
      "episcopalian",
      "satanism",
      "baptist",
    ],
    sound: "sounds/church-bell.mp3",
    icon: "church.png",
  },
  mosque: {
    id: "mosque",
    name: "Mosque",
    subtitle: "Islamic community",
    tags: [
      "mosque",
      "islam",
      "muslim",
      "allah",
      "quran",
      "ramadan",
      "kaaba",
      "mecca",
      "hajj",
    ],
    sound: "sounds/muhammad.mp3",
    icon: "mosque.png",
  },
  synagogue: {
    id: "synagogue",
    name: "Synagogue",
    subtitle: "Jewish community",
    tags: [
      "synagogue",
      "judaism",
      "jewish",
      "torah",
      "yahweh",
      "faith",
      "talmud",
      "kabbalah",
      "hanukkah",
    ],
    sound: "sounds/star-of-david.mp3",
    icon: "synagogue.png",
  },
  temple: {
    id: "temple",
    name: "Temple",
    subtitle: "Devotion",
    tags: [
      "temple",
      "buddhism",
      "meditation",
      "spirituality",
      "zen",
      "nirvana",
      "dharma",
      "sangha",
      "lotus",
    ],
    sound: "sounds/buddha.mp3",
    icon: "temple.png",
  },
  mandir: {
    id: "mandir",
    name: "Mandir",
    subtitle: "Worship",
    tags: [
      "mandir",
      "hinduism",
      "vedic",
      "krishna",
      "rama",
      "dharma",
      "yoga",
      "moksha",
      "puja",
      "bhakti",
    ],
    sound: "sounds/brahma.mp3",
    icon: "mandir.png",
  },
  market: {
    id: "market",
    name: "Market",
    subtitle: "Buy / Sell / Trade",
    tags: ["market", "trade", "commerce", "economy", "bitcoin", "crypto"],
    sound: "sounds/market.mp3",
    icon: "market.png",
  },
  news: {
    id: "news",
    name: "News",
    subtitle: "World events",
    tags: [
      "news",
      "media",
      "journalism",
      "reporting",
      "currentevents",
      "worldnews",
      "updates",
    ],
    sound: "sounds/news.mp3",
    icon: "news.png",
    externalUrl: "https://www.oann.com/",
  },
}
