name: PageSpeed Insights

on:
  push:
    branches: [ main ]

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Debug info
        run: |
          echo "Node version: $(node --version)"
          echo "Yarn version: $(yarn --version)"
          echo "Current directory: $(pwd)"
          echo "Directory contents: $(ls -la)"
        
      - name: Run PageSpeed Insights
        uses: GoogleChromeLabs/lighthouse-ci@v9.0.0
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: .lighthouserc.js 